apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      run: new-nginx
  template:
    metadata:
      labels:
        run: new-nginx
    spec:
      containers:
      - name: new-nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: new
          mountPath: /usr/share/nginx/html
      volumes:
      - name: new
        hostPath:
          path: /www
---
apiVersion: v1
kind: Service
metadata:
  name: new-nginx
spec:
  selector:
    run: new-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "www.good.com"
    http:
      paths:
      - pathType: Prefix
        path: /new/new/
        backend:
          service:
            name: new-nginx
            port:
              number: 80

